In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
df = pd.read_excel('video-classification.xlsx', sheet_name = 'Sheet1')
df
# df.columns.values.tolist()

,Video,BG,P1,P2,P3,P4,P5,P6,P7,P8,...,P15,P16,P17,P18,P19,P20,Haidar,P11R,Bernardo,P2398
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rid-D2T5-P,...,NaN,NaN,NaN,NaN,Ext-C5J1-P,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ext-C5-P,...,NaN,NaN,NaN,NaN,ExtO-C5J1-L,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rid-B5J2-L,...,NaN,NaN,NaN,NaN,ExtIntRid-B4T2C2J4-HP,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Rid-M4B3-L,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,IntRid-B2J4-L,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rid-M4D4B5T3A1C2-H,NaN,NaN
97,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
row_read = df.P19[2]

code = row_read.split('-')
print(code)

exc = str(code[0])
mech = list(code[1])
mot = list(code[2])

excitations = re.sub( r"([A-Z])", r" \1", exc).split() # From here https://stackoverflow.com/questions/2277352/split-a-string-at-uppercase-letters
print(excitations)

mechanisms = []
for i in range(int(len(mech)/2)):
    mechanisms.append(mech[i*2] + mech[i*2+1])

print(mechanisms)

print(mot)

['ExtIntRid', 'B4T2C2J4', 'HP']
['Ext', 'Int', 'Rid']
['B4', 'T2', 'C2', 'J4']
['H', 'P']

In [6]:
for j in range(0,15):
    row_read = df.P19[j]
    
    if row_read == row_read:
        
        vid = j+1

        print('Video:', vid)

        code = row_read.split('-')
        print('Code:', code)

        exc = str(code[0])
        mech = list(code[1])
        mot = list(code[2])

        excitations = re.sub( r"([A-Z])", r" \1", exc).split() # From here https://stackoverflow.com/questions/2277352/split-a-string-at-uppercase-letters
        print('Excitations:', excitations)

        mechanisms = []
        for k in range(int(len(mech)/2)):
            mechanisms.append(mech[k*2] + mech[k*2+1])

        for ii in mechanisms:
            mechanism = ii[0]
            weight = ii[1]

        print('Mechanisms:', mechanisms)

        print('Motion:', mot)

        mech2 = dict(mechanisms)
        print(mech2)
        print('\n')

Video: 1
Code: ['Ext', 'C5J1', 'P']
Excitations: ['Ext']
Mechanisms: ['C5', 'J1']
Motion: ['P']
{'C': '5', 'J': '1'}


Video: 2
Code: ['ExtO', 'C5J1', 'L']
Excitations: ['Ext', 'O']
Mechanisms: ['C5', 'J1']
Motion: ['L']
{'C': '5', 'J': '1'}


Video: 3
Code: ['ExtIntRid', 'B4T2C2J4', 'HP']
Excitations: ['Ext', 'Int', 'Rid']
Mechanisms: ['B4', 'T2', 'C2', 'J4']
Motion: ['H', 'P']
{'B': '4', 'T': '2', 'C': '2', 'J': '4'}


Video: 4
Code: ['Rid', 'M4B3', 'L']
Excitations: ['Rid']
Mechanisms: ['M4', 'B3']
Motion: ['L']
{'M': '4', 'B': '3'}


Video: 5
Code: ['IntRid', 'B2J4', 'L']
Excitations: ['Int', 'Rid']
Mechanisms: ['B2', 'J4']
Motion: ['L']
{'B': '2', 'J': '4'}


Video: 6
Code: ['IntRid', 'B2T4', 'H']
Excitations: ['Int', 'Rid']
Mechanisms: ['B2', 'T4']
Motion: ['H']
{'B': '2', 'T': '4'}


Video: 7
Code: ['Rid', 'M5B1T1', 'H']
Excitations: ['Rid']
Mechanisms: ['M5', 'B1', 'T1']
Motion: ['H']
{'M': '5', 'B': '1', 'T': '1'}


Video: 8
Code: ['ExtRid', 'M1B3T3C3', 'H']
Excitations: ['Ext', 'Rid']
Mechanisms: ['M1', 'B3', 'T3', 'C3']
Motion: ['H']
{'M': '1', 'B': '3', 'T': '3', 'C': '3'}


Video: 9
Code: ['Rid', 'C5', 'P']
Excitations: ['Rid']
Mechanisms: ['C5']
Motion: ['P']
{'C': '5'}


Video: 10
Code: ['Rid', 'B1C5', 'P']
Excitations: ['Rid']
Mechanisms: ['B1', 'C5']
Motion: ['P']
{'B': '1', 'C': '5'}

In [5]:
rows, columns = df.shape

for i in range(columns):
    for j in range(rows):

SyntaxError: incomplete input (1470780481.py, line 5)